### PR TITLE
Allows access to WebJEAUsername in onload script, fixes #4

### LINKED ISSUE #4: Access to WebJEAUsername in OnloadScript
Access to the $WebJEAUsername in the OnloadScript would be great improvement.

This way I could present information or prepare links for the calling user.

### PR DESCRIPTION
**Pull request by phoerr**
This change enables passing parameters into the onload script. The key thing we can use with this is accessing the `$WebJEAUsername` variable in the onload to present options based on the username.

### CODE REVIEW

**Comment by btimmerm** [comment]
This works great! Thanks @phoerr!

**Comment by btimmerm** [comment]
Hi @markdomansky, any chance you could review this?

**Comment by phoerr** [comment]
Please consider adding this change, even if not this exact PR. 

I've had this modification running in our production instances of WebJEA for months without issue.

**Comment by markdomansky** [comment]
I'll try to look into this in the next couple weeks.

**Review by markdomansky — APPROVED** [review]

**Pull request merged**
